export const LOAN_REQUEST_SERVICE = 'LOAN_REQUESTS';
export const CREDIT_BUREAU_REQUEST_SERVICE = 'CREDIT_BUREAU_REQUEST';
export const CREDIT_BUREAU_RESPONSE_SERVICE = 'CREDIT_BUREAU_RESPONSE';
export const LOAN_SIM_REQ_BRD = 'BRD';
export const LOAN_SIM_REQ_BT = 'BT';
export const LOAN_SIM_REQ_ING = 'ING';
export const BANKS_SIMULATION_RESPONSES = 'BANKS_SIMULATION_RESPONSES';
